[package]
name = "smt-toggle"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14", features = ["tokio"] }
tray-icon = "0.21.3"
tokio = { version = "1", features = ["process", "rt-multi-thread"] }
gtk = "0.18"
